# -*- coding: utf-8 -*-
"""vehicle_routing_problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRuUvV5lKD4zWniPBCMpfmii9CelQi_i
"""

from gurobipy import Model, GRB

# OPTIGUIDE DATA CODE GOES HERE

# Customer demands (0 is depot)
demand = {
    0: 0,
    1: 10,
    2: 15,
    3: 20,
    4: 25,
    5: 30,
    6: 35
}

# Vehicle parameters
vehicle_count = 4
vehicle_capacity = 60

# List of all nodes
customers = list(demand.keys())

# Distance matrix (example symmetric distances)
distance_data = [
    [0, 8, 12, 20, 15, 30, 25],
    [8, 0, 5, 18, 9, 22, 11],
    [12, 5, 0, 10, 7, 20, 13],
    [20, 18, 10, 0, 5, 14, 10],
    [15, 9, 7, 5, 0, 10, 8],
    [30, 22, 20, 14, 10, 0, 5],
    [25, 11, 13, 10, 8, 5, 0],
]

# Distance dictionary (only i != j)
distance = {(i, j): distance_data[i][j] for i in customers for j in customers if i != j}

# Create model
model = Model("CVRP_Custom")

# Decision variables: x[i,j] = 1 if edge (i,j) is used
x = model.addVars(distance.keys(), vtype=GRB.BINARY, name="x")

# Load variables for MTZ subtour elimination
u = model.addVars(customers, lb=0, ub=vehicle_capacity, vtype=GRB.CONTINUOUS, name="load")

# OPTIGUIDE CONSTRAINT CODE GOES HERE

# Each customer visited exactly once
for j in customers[1:]:
    model.addConstr(sum(x[i, j] for i in customers if i != j) == 1, name=f"visit_in_{j}")
    model.addConstr(sum(x[j, k] for k in customers if k != j) == 1, name=f"visit_out_{j}")

# Number of vehicles leaving and returning to depot equals vehicle_count
model.addConstr(sum(x[0, j] for j in customers if j != 0) == vehicle_count, name="depot_departure")
model.addConstr(sum(x[i, 0] for i in customers if i != 0) == vehicle_count, name="depot_return")

# MTZ subtour elimination constraints
for i in customers[1:]:
    for j in customers[1:]:
        if i != j:
            model.addConstr(
                u[i] - u[j] + vehicle_capacity * x[i, j] <= vehicle_capacity - demand[j],
                name=f"subtour_{i}_{j}"
            )

# Load limits (demand <= load <= vehicle capacity)
for i in customers[1:]:
    model.addConstr(u[i] >= demand[i], name=f"minload_{i}")
    model.addConstr(u[i] <= vehicle_capacity, name=f"maxload_{i}")

# Objective: minimize total travel distance
model.setObjective(
    sum(distance[i, j] * x[i, j] for i, j in distance),
    GRB.MINIMIZE
)

# --- Solve the model ---
model.optimize()
m = model

# Display results if optimal solution is found
if model.status == GRB.OPTIMAL:
    print(f"✅ Optimal solution found. Total cost: {model.ObjVal:.2f}")
    for v in model.getVars():
        if v.X > 0:
            print(f"{v.VarName}: {v.X}")
else:
    print("❌ No feasible solution found.")

