# -*- coding: utf-8 -*-
"""vehicle_routing_problem_Gurobi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R579E7SjSJKldTkqx1vDLyOozWZxY-t1
"""

def solve_model():
    # Modelin tüm kodu buraya gelecek, indentli yani 4 boşluk içeride
    # Örneğin:
    customers = [0, 1, 2, 3, 4, 5, 6]
    demand = {0:0, 1:10, 2:15, 3:20, 4:25, 5:30, 6:35}
    vehicle_count = 4
    vehicle_capacity = 60

    # Modelin geri kalanı...

    model.optimize()

    total_distance = model.objVal  # Burada sonucu bir değişkene atıyorsun
    return total_distance           # Ve fonksiyon sonunda bu değeri döndürüyorsun